import { distanceUnit, formatDistance, inputDistance, storedDistance, preferences, today } from "../format";
/* Hallmark · component: management dialogs · genre: atmospheric · theme: clean garage counter
 * states: default · hover · focus · active · disabled · loading · error · success
 * contrast: pass (46–50)
 */
import { ArrowDown, ArrowUp, Check, LoaderCircle, Plus, Trash2, X } from "lucide-react";
import { Children, cloneElement, isValidElement, useId, useEffect, useRef, useState } from "react";
import { api, type DocumentRecord, type MaintenanceRecord, type Project, type ProjectInput, type ReferenceSpec, type Reminder, type ReminderInput, type SpecInput, type Vehicle, type VehicleUpdateInput } from "../api";
import { SelectOrCustom } from "./SelectOrCustom";
import { PhotoPreview } from "./PhotoEditor";

type Status = "idle" | "loading" | "success" | "error";

function Shell({ open, title, kicker, status, error, onClose, onSubmit, onDelete, deleteLabel = "Delete", deleteConfirmation, deleteOnly = false, children, saveLabel = "Save changes" }: { open: boolean; title: string; kicker: string; status: Status; error: string; onClose: () => void; onSubmit: (event: React.FormEvent) => void; onDelete?: () => Promise<void>; deleteLabel?: string; deleteConfirmation?: { phrase: string; message: string }; deleteOnly?: boolean; children?: React.ReactNode; saveLabel?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  const [confirmingDelete, setConfirmingDelete] = useState(deleteOnly);
  const [deletePhrase, setDeletePhrase] = useState("");
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState("");
  const busy = status === "loading" || deleting;
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) { setConfirmingDelete(deleteOnly); setDeletePhrase(""); setDeleteError(""); setDeleting(false); dialog.showModal(); requestAnimationFrame(() => dialog.querySelector<HTMLElement>("[autofocus], input:not([type=hidden]), select, textarea")?.focus()); } else if (!open && dialog.open) dialog.close(); }, [open, deleteOnly]);
  const close = () => { if (!busy) onClose(); };
  const confirmed = !deleteConfirmation || deletePhrase === deleteConfirmation.phrase;
  const remove = async () => {
    if (!onDelete || !confirmed || busy) return;
    setDeleting(true); setDeleteError("");
    try { await onDelete(); onClose(); } catch (cause) { setDeleteError(cause instanceof Error ? cause.message : "Deletion failed. Your record has not been removed."); } finally { setDeleting(false); }
  };
  return (
    <dialog ref={ref} className="maintenance-dialog" aria-label={title} onMouseDown={(event) => { if (event.target === ref.current) close(); }} onCancel={(event) => { event.preventDefault(); close(); }} onClose={onClose}>
      <form onSubmit={(event) => { if (busy || status === "success") { event.preventDefault(); return; } if (confirmingDelete) { event.preventDefault(); void remove(); } else onSubmit(event); }} noValidate aria-busy={busy}>
        <header className="dialog__header"><div><h2>{title}</h2><span className="dialog__context">{kicker}</span></div><button type="button" className="icon-button" onClick={close} disabled={busy} aria-label={`Close ${title.toLowerCase()}`}><X size={19} /></button></header>
        {!deleteOnly && <div className="form-grid">{children}</div>}
        {confirmingDelete && <div className="delete-confirm" role="alert"><strong>Delete permanently?</strong><p>{deleteConfirmation?.message ?? "This permanently removes the record."}</p>{deleteConfirmation && <label><span>Type <code>{deleteConfirmation.phrase}</code> to confirm</span><input autoFocus value={deletePhrase} onChange={(event) => setDeletePhrase(event.target.value)} autoComplete="off" /></label>}{!deleteOnly && <button type="button" className="button button--quiet button--small" onClick={() => setConfirmingDelete(false)} disabled={busy}>Keep record</button>}</div>}
        <div className="dialog__status" aria-live="polite">{deleteError || error || (status === "success" ? "Saved." : "")}</div>
        <footer className="dialog__footer dialog__footer--split">
          {onDelete ? <button type="button" className="button button--destructive-quiet" disabled={busy || (confirmingDelete && !confirmed)} onClick={() => { if (!confirmingDelete) setConfirmingDelete(true); else void remove(); }}><Trash2 size={16} />{deleting ? "Deleting…" : confirmingDelete ? "Confirm delete" : deleteLabel === "Delete" ? "Delete" : `Delete ${deleteLabel}`}</button> : <span />}
          <div className="dialog__footer-actions"><button type="button" className="button button--quiet" onClick={close} disabled={busy}>{deleteOnly ? "Keep vehicle" : "Cancel"}</button>{!deleteOnly && <button type="submit" className="button button--primary" disabled={busy || status === "success" || confirmingDelete} data-state={status}>{status === "loading" ? <><LoaderCircle className="spin" size={16} />Working…</> : status === "success" ? <><Check size={16} />Saved</> : saveLabel}</button>}</div>
        </footer>
      </form>
    </dialog>
  );
}

function labelControls(node: React.ReactNode, label: string, controlId: string): React.ReactNode {
  return Children.map(node, (child) => {
    if (!isValidElement(child)) return child;
    const element = child as React.ReactElement<{ children?: React.ReactNode; "aria-label"?: string; id?: string }>;
    if (typeof element.type === "string" && ["input", "select", "textarea"].includes(element.type)) return cloneElement(element, { id: controlId, "aria-label": element.props["aria-label"] ?? label });
    return element.props.children ? cloneElement(element, { children: labelControls(element.props.children, label, controlId) }) : element;
  });
}
function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { const controlId = useId(); return <div className="field" data-span={wide ? "wide" : undefined}><label htmlFor={controlId}>{label}</label>{labelControls(children, label, controlId)}<span className="field__help">&nbsp;</span></div>; }
function valueOrEmpty(value: string | null | undefined) { return value ?? ""; }

export function vehicleDeleteConfirmation(vehicle: Vehicle) {
  return {
    phrase: vehicle.nickname?.trim() || `${vehicle.year} ${vehicle.make} ${vehicle.model}`,
    message: "This removes the vehicle, maintenance history and audit trail, mileage, specifications, projects, schedules, reminders, photos, and documents. Inventory parts remain, but their vehicle fitment link is removed.",
  };
}

export function VehicleDeleteDialog({ vehicle, onClose, onDelete }: { vehicle: Vehicle; onClose: () => void; onDelete: (vehicle: Vehicle) => Promise<void> }) {
  return <Shell open title="Delete vehicle" kicker={`${vehicle.year} ${vehicle.make} ${vehicle.model}${vehicle.nickname ? ` · ${vehicle.nickname}` : ""}`} status="idle" error="" onClose={onClose} onSubmit={(event) => event.preventDefault()} onDelete={() => onDelete(vehicle)} deleteOnly deleteConfirmation={vehicleDeleteConfirmation(vehicle)} />;
}

export function VehicleEditDialog({ open, vehicle, vehicles, onClose, onSave, onDelete }: { open: boolean; vehicle: Vehicle; vehicles: Vehicle[]; onClose: () => void; onSave: (input: VehicleUpdateInput) => Promise<void>; onDelete: (vehicle: Vehicle) => Promise<void> }) {
  const [form, setForm] = useState({
    vin: "", year: "", make: "", model: "", trim: "", nickname: "", mileage: "", mileageDate: today(), annualMileageEstimate: "",
    color: "", bodyStyle: "", fuelType: "", drivetrain: "", engine: "", transmission: "", licensePlate: "", registrationState: "", registrationNumber: "",
    purchaseDate: "", purchasePrice: "", registrationExpiresAt: "", notes: "",
  });
  const [status, setStatus] = useState<Status>("idle");
  const [error, setError] = useState("");
  const [decoding, setDecoding] = useState(false);
  useEffect(() => { if (open) { setForm({
    vin: valueOrEmpty(vehicle.vin), year: String(vehicle.year), make: vehicle.make, model: vehicle.model, trim: valueOrEmpty(vehicle.trim), nickname: valueOrEmpty(vehicle.nickname),
    mileage: inputDistance(vehicle.mileage), mileageDate: today(), annualMileageEstimate: vehicle.annualMileageEstimate == null ? "" : inputDistance(vehicle.annualMileageEstimate),
    color: valueOrEmpty(vehicle.color), bodyStyle: valueOrEmpty(vehicle.bodyStyle), fuelType: valueOrEmpty(vehicle.fuelType), drivetrain: valueOrEmpty(vehicle.drivetrain),
    engine: valueOrEmpty(vehicle.engine), transmission: valueOrEmpty(vehicle.transmission), licensePlate: valueOrEmpty(vehicle.licensePlate), registrationState: valueOrEmpty(vehicle.registrationState),
    registrationNumber: valueOrEmpty(vehicle.registrationNumber), purchaseDate: valueOrEmpty(vehicle.purchaseDate), purchasePrice: vehicle.purchasePriceCents == null ? "" : String(vehicle.purchasePriceCents / 100),
    registrationExpiresAt: valueOrEmpty(vehicle.registrationExpiresAt), notes: valueOrEmpty(vehicle.notes),
  }); setStatus("idle"); setError(""); } }, [open, vehicle]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const decode = async () => { if (form.vin.length < 11) { setError("Enter at least 11 VIN characters before decoding."); setStatus("error"); return; } setDecoding(true); setError(""); try { const data = await api.decodeVin(form.vin); setForm((current) => ({ ...current, year: data.year ? String(data.year) : current.year, make: data.make || current.make, model: data.model || current.model, trim: data.trim || current.trim, engine: data.engine || current.engine, transmission: data.transmission || current.transmission, bodyStyle: data.bodyClass || current.bodyStyle, fuelType: data.fuelType || current.fuelType })); setStatus("idle"); } catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message : "The VIN could not be decoded."); } finally { setDecoding(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.make.trim() || !form.model.trim() || Number(form.year) < 1886 || Number(form.mileage) < 0) { setError("Enter a valid year, make, model, and current mileage."); setStatus("error"); return; } setStatus("loading"); setError(""); try { await onSave({ ...form, year: Number(form.year), mileage: storedDistance(form.mileage), annualMileageEstimate: form.annualMileageEstimate ? storedDistance(form.annualMileageEstimate) : null, purchasePrice: form.purchasePrice ? Number(form.purchasePrice) : null }); setStatus("success"); setTimeout(onClose, 400); } catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message : "The vehicle could not be updated."); } };
  return <Shell open={open} title="Edit vehicle" kicker={`${vehicle.year} ${vehicle.make} ${vehicle.model}`} status={status} error={error} onClose={onClose} onSubmit={submit} onDelete={() => onDelete(vehicle)} deleteLabel="vehicle" deleteConfirmation={vehicleDeleteConfirmation(vehicle)}>
    <fieldset className="form-section" data-span="wide"><legend>Identity</legend><div className="form-section__grid"><Field label="VIN" wide><div className="inline-field"><input autoFocus value={form.vin} maxLength={17} onChange={(e) => update("vin", e.target.value.toUpperCase())} /><button type="button" className="button button--quiet" onClick={() => void decode()} disabled={decoding}>{decoding ? "Decoding…" : "Decode VIN"}</button></div></Field><Field label="Year"><input type="number" min="1886" value={form.year} onChange={(e) => update("year", e.target.value)} /></Field><Field label="Make"><SelectOrCustom label="Make" value={form.make} options={vehicles.map((item) => item.make)} onChange={(value) => update("make", value)} placeholder="e.g. Toyota" emptyLabel="Choose or add a make" /></Field><Field label="Model"><SelectOrCustom label="Model" value={form.model} options={vehicles.map((item) => item.model)} onChange={(value) => update("model", value)} placeholder="e.g. Tacoma" emptyLabel="Choose or add a model" /></Field><Field label="Trim"><SelectOrCustom label="Trim" value={form.trim} options={vehicles.map((item) => item.trim ?? "")} onChange={(value) => update("trim", value)} placeholder="e.g. Limited" emptyLabel="No trim recorded" /></Field><Field label="Nickname"><input value={form.nickname} onChange={(e) => update("nickname", e.target.value)} /></Field><Field label={`Current mileage (${distanceUnit()})`}><input type="number" min="0" value={form.mileage} onChange={(e) => update("mileage", e.target.value)} /></Field><Field label="Mileage date"><input type="date" value={form.mileageDate} onChange={(e) => update("mileageDate", e.target.value)} /></Field><Field label={`Yearly mileage estimate (${distanceUnit()})`}><input type="number" min="0" value={form.annualMileageEstimate} onChange={(e) => update("annualMileageEstimate", e.target.value)} /></Field></div></fieldset>
    <fieldset className="form-section" data-span="wide"><legend>Mechanical</legend><div className="form-section__grid"><Field label="Color"><SelectOrCustom label="Color" value={form.color} options={["Black", "White", "Silver", "Gray", "Red", "Blue", "Green", "Yellow", ...vehicles.map((item) => item.color ?? "")]} onChange={(value) => update("color", value)} placeholder="e.g. Blue" emptyLabel="No color recorded" /></Field><Field label="Body style"><SelectOrCustom label="Body style" value={form.bodyStyle} options={["Sedan", "Coupe", "Hatchback", "Wagon", "SUV", "Crossover", "Pickup", "Van", "Convertible", "Motorcycle", ...vehicles.map((item) => item.bodyStyle ?? "")]} onChange={(value) => update("bodyStyle", value)} placeholder="e.g. SUV" emptyLabel="No body style recorded" /></Field><Field label="Fuel type"><SelectOrCustom label="Fuel type" value={form.fuelType} options={["Gasoline", "Diesel", "Hybrid", "Plug-in hybrid", "Electric", "Flex fuel", ...vehicles.map((item) => item.fuelType ?? "")]} onChange={(value) => update("fuelType", value)} placeholder="e.g. Electric" emptyLabel="No fuel type recorded" /></Field><Field label="Drivetrain"><SelectOrCustom label="Drivetrain" value={form.drivetrain} options={["FWD", "RWD", "AWD", "4WD", ...vehicles.map((item) => item.drivetrain ?? "")]} onChange={(value) => update("drivetrain", value)} placeholder="e.g. AWD" emptyLabel="No drivetrain recorded" /></Field><Field label="Engine" wide><SelectOrCustom label="Engine" value={form.engine} options={vehicles.map((item) => item.engine ?? "")} onChange={(value) => update("engine", value)} placeholder="e.g. 2.0L turbo" emptyLabel="No engine recorded" /></Field><Field label="Transmission" wide><SelectOrCustom label="Transmission" value={form.transmission} options={["Automatic", "Manual", "CVT", "DCT", ...vehicles.map((item) => item.transmission ?? "")]} onChange={(value) => update("transmission", value)} placeholder="e.g. 8-speed automatic" emptyLabel="No transmission recorded" /></Field></div></fieldset>
    <fieldset className="form-section" data-span="wide"><legend>Ownership & registration</legend><div className="form-section__grid"><Field label="License plate"><input value={form.licensePlate} onChange={(e) => update("licensePlate", e.target.value)} /></Field><Field label="State / province"><input value={form.registrationState} onChange={(e) => update("registrationState", e.target.value)} /></Field><Field label="Registration number"><input value={form.registrationNumber} onChange={(e) => update("registrationNumber", e.target.value)} /></Field><Field label="Registration expires"><input type="date" value={form.registrationExpiresAt} onChange={(e) => update("registrationExpiresAt", e.target.value)} /></Field><Field label="Purchase date"><input type="date" value={form.purchaseDate} onChange={(e) => update("purchaseDate", e.target.value)} /></Field><Field label="Purchase price"><input type="number" min="0" step="0.01" value={form.purchasePrice} onChange={(e) => update("purchasePrice", e.target.value)} /></Field></div></fieldset>
    <p className="field-note" data-span="wide">Insurance policies and their documents are managed from Insurance so they remain after deleting a vehicle.</p>
    <Field label="Vehicle notes" wide><textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} /></Field>
  </Shell>;
}

export function SpecDialog({ open, spec, groups, onClose, onSave, onDelete }: { open: boolean; spec: ReferenceSpec | null; groups: string[]; onClose: () => void; onSave: (input: SpecInput) => Promise<void>; onDelete: (spec: ReferenceSpec) => Promise<void> }) {
  const [form, setForm] = useState({ groupName: "Engine", label: "", value: "", source: "", notes: "" }); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState("");
  useEffect(() => { if (open) { setForm({ groupName: spec?.groupName ?? "Engine", label: spec?.label ?? "", value: spec?.value ?? "", source: spec?.source ?? "", notes: spec?.notes ?? "" }); setStatus("idle"); setError(""); } }, [open, spec]); const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus("loading"); try { await onSave(form); setStatus("success"); setTimeout(onClose, 350); } catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message : "The specification could not be saved."); } };
  return <Shell open={open} title={spec ? "Edit specification" : "Add specification"} kicker="Torque and fluid reference" status={status} error={error} onClose={onClose} onSubmit={submit} onDelete={spec ? async () => { await onDelete(spec); onClose(); } : undefined}><Field label="Group"><SelectOrCustom label="Specification group" value={form.groupName} options={["Engine", "Fluids", "Brakes", "Suspension", "Electrical", "Wheels", ...groups]} onChange={(groupName) => update("groupName", groupName)} placeholder="e.g. Cooling" emptyLabel="Choose or add a group" /></Field><Field label="Label"><input value={form.label} onChange={(e) => update("label", e.target.value)} placeholder="Lug nut torque" /></Field><Field label="Value" wide><input value={form.value} onChange={(e) => update("value", e.target.value)} placeholder="100 Nm / 74 lb-ft" /></Field><Field label="Source" wide><input value={form.source} onChange={(e) => update("source", e.target.value)} placeholder="Factory service manual, page 42" /></Field><Field label="Notes" wide><textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} /></Field></Shell>;
}



export function ProjectDialog({ open, project, onClose, onSave, onDelete }: { open: boolean; project: Project | null; onClose: () => void; onSave: (input: ProjectInput) => Promise<void>; onDelete: (project: Project) => Promise<void> }) {
  type DraftTask = { id?: number; title: string; completed: boolean; estimatedCost: string };
  const [form, setForm] = useState({ title: "", description: "", status: "Backlog" as ProjectInput["status"], estimatedBudget: "", actualCost: "", targetDate: "" });
  const [tasks, setTasks] = useState<DraftTask[]>([]); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState("");
  useEffect(() => { if (open) { setForm({ title: project?.title ?? "", description: project?.description ?? "", status: (project?.status as ProjectInput["status"]) ?? "Backlog", estimatedBudget: project ? String(project.estimatedBudgetCents / 100) : "", actualCost: project ? String(project.actualCostCents / 100) : "", targetDate: project?.targetDate ?? "" }); setTasks(project?.tasks.map((task) => ({ id: task.id, title: task.title, completed: task.completed, estimatedCost: task.estimatedCostCents ? String(task.estimatedCostCents / 100) : "" })) ?? []); setStatus("idle"); setError(""); } }, [open, project]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const moveTask = (index: number, offset: number) => setTasks((current) => { const next = [...current]; [next[index], next[index + offset]] = [next[index + offset], next[index]]; return next; });
  const updateTask = (index: number, patch: Partial<DraftTask>) => setTasks((current) => current.map((task, position) => position === index ? { ...task, ...patch } : task));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (form.title.trim().length < 2 || tasks.some((task) => !task.title.trim())) { setError("Add a project name and complete or remove blank tasks."); setStatus("error"); return; } setStatus("loading"); setError(""); try { await onSave({ ...form, estimatedBudget: Number(form.estimatedBudget || 0), actualCost: Number(form.actualCost || 0), tasks: tasks.map((task) => ({ id: task.id, title: task.title.trim(), completed: task.completed, estimatedCost: Number(task.estimatedCost || 0) })) }); setStatus("success"); setTimeout(onClose, 350); } catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message : "The project could not be saved."); } };
  return <Shell open={open} title={project ? "Edit project" : "New project"} kicker="Build planner" status={status} error={error} onClose={onClose} onSubmit={submit} onDelete={project ? async () => { await onDelete(project); onClose(); } : undefined}><Field label="Project name" wide><input autoFocus value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="Clutch replacement" /></Field><Field label="Status"><select value={form.status} onChange={(e) => update("status", e.target.value)}>{["Backlog","Planned","In Progress","Waiting","Done"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Target date"><input type="date" value={form.targetDate} onChange={(e) => update("targetDate", e.target.value)} /></Field><Field label="Estimated budget"><input type="number" min="0" step="0.01" value={form.estimatedBudget} onChange={(e) => update("estimatedBudget", e.target.value)} /></Field><Field label="Actual cost"><input type="number" min="0" step="0.01" value={form.actualCost} onChange={(e) => update("actualCost", e.target.value)} /></Field><Field label="Description" wide><textarea value={form.description} onChange={(e) => update("description", e.target.value)} /></Field><fieldset className="task-editor" data-span="wide"><legend>Project checklist</legend>{tasks.length ? tasks.map((task, index) => <div className="task-editor__row" key={task.id ?? index}><input type="checkbox" checked={task.completed} onChange={(event) => updateTask(index, { completed: event.target.checked })} aria-label={`Mark task ${index + 1} complete`} /><input value={task.title} onChange={(event) => updateTask(index, { title: event.target.value })} placeholder="Task description" aria-label={`Task ${index + 1} description`} /><input type="number" min="0" step="0.01" value={task.estimatedCost} onChange={(event) => updateTask(index, { estimatedCost: event.target.value })} placeholder="Cost" aria-label={`Task ${index + 1} estimated cost`} /><button type="button" className="icon-button" disabled={index === 0} onClick={() => moveTask(index, -1)} aria-label={`Move task ${index + 1} up`}><ArrowUp size={15} /></button><button type="button" className="icon-button" disabled={index === tasks.length - 1} onClick={() => moveTask(index, 1)} aria-label={`Move task ${index + 1} down`}><ArrowDown size={15} /></button><button type="button" className="icon-button" onClick={() => setTasks((current) => current.filter((_, position) => position !== index))} aria-label={`Remove task ${index + 1}`}><Trash2 size={15} /></button></div>) : <p className="field-note">No checklist items yet.</p>}<button type="button" className="button button--quiet button--small" onClick={() => setTasks((current) => [...current, { title: "", completed: false, estimatedCost: "" }])}><Plus size={15} />Add task</button></fieldset></Shell>;
}

export function DocumentDialog({ open, document, vehicles, activeVehicleId, onClose, onUpload, onSave, onDelete }: { open: boolean; document: DocumentRecord | null; vehicles: Vehicle[]; activeVehicleId: number | null; onClose: () => void; onUpload: (input: { vehicleId: number; maintenanceIds: number[]; kind: string; name: string; notes?: string; file: File }) => Promise<void>; onSave: (document: DocumentRecord, input: { notes?: string; name: string; kind: string; vehicleId: number | null; maintenanceIds: number[] }) => Promise<void>; onDelete: (document: DocumentRecord) => Promise<void> }) {
  const [notes, setNotes] = useState(""); const [name, setName] = useState(""); const [kind, setKind] = useState("Manual"); const [vehicleId, setVehicleId] = useState(String(activeVehicleId)); const [file, setFile] = useState<File | null>(null); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState("");
  const [maintenance, setMaintenance] = useState<MaintenanceRecord[]>([]); const [maintenanceSearch, setMaintenanceSearch] = useState(""); const [maintenanceIds, setMaintenanceIds] = useState<number[]>([]);
  useEffect(() => { if (open) { setNotes(document?.notes ?? ""); setName(document?.name ?? ""); setKind(document?.kind ?? "Manual"); setVehicleId(String(document ? document.vehicleId ?? "" : activeVehicleId ?? "")); setFile(null); setMaintenanceSearch(""); setMaintenanceIds(document?.maintenanceIds ?? (document?.maintenanceId ? [document.maintenanceId] : [])); setStatus("idle"); setError(""); } }, [open, document, activeVehicleId]);
  useEffect(() => {
    if (!open || !Number(vehicleId) || document?.insurancePolicyId) { setMaintenance([]); return; }
    let active = true; api.maintenance(Number(vehicleId)).then((rows) => { if (active) setMaintenance(rows); }).catch(() => { if (active) setMaintenance([]); });
    return () => { active = false; };
  }, [open, vehicleId, document?.insurancePolicyId]);
  const selectVehicle = (value: string) => { setVehicleId(value); setMaintenanceIds([]); setMaintenanceSearch(""); };
  const toggleMaintenance = (id: number) => setMaintenanceIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const normalizedSearch = maintenanceSearch.trim().toLocaleLowerCase();
  const matchingMaintenance = maintenance.filter((record) => !normalizedSearch || [record.title, record.category, record.serviceDate, record.shopName, record.mileage].filter((value) => value != null).join(" ").toLocaleLowerCase().includes(normalizedSearch));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus("loading"); try { if (!name.trim()) throw new Error("Enter a display name."); if (document) await onSave(document, { name: name.trim(), kind, notes, vehicleId: document.insurancePolicyId ? null : Number(vehicleId) || null, maintenanceIds: document.insurancePolicyId ? [] : maintenanceIds }); else { if (!file) throw new Error("Choose a file to upload."); await onUpload({ vehicleId: Number(vehicleId), maintenanceIds, kind, name: name.trim(), notes, file }); } setStatus("success"); setTimeout(onClose, 350); } catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message : "The document could not be saved."); } };
  return <Shell open={open} title={document ? "Edit document" : "Add document"} kicker="Garage archive" status={status} error={error} onClose={onClose} onSubmit={submit} onDelete={document ? async () => { await onDelete(document); onClose(); } : undefined} saveLabel={document ? "Save changes" : "Upload document"}>
    <Field label="Display name" wide><input value={name} onChange={(e) => setName(e.target.value)} placeholder="AutoZone Receipt 2026-09-08" maxLength={240} /><small className="field-note">Editable and searchable. Changing this does not rename or replace the stored file.</small></Field>
    <Field label="Notes" wide><textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={10000} placeholder="Optional searchable details" /></Field>
    {document && <div className="document-identity" data-span="wide"><div><span>Tracking ID</span><code>{document.trackingId || `Legacy-${document.id}`}</code></div><div><span>Original filename</span><strong>{document.originalName || document.name}</strong></div></div>}
    {document?.mimeType?.startsWith("image/") && <Field label="Photo" wide><div className="document-photo-adjust"><PhotoPreview id={document.id} name={document.name} className="record-preview" /><small className="field-note">Select the image to open the full-size rotation editor.</small></div></Field>}
    <Field label="Vehicle"><select disabled={Boolean(document?.insurancePolicyId)} value={vehicleId} onChange={(e) => selectVehicle(e.target.value)}><option value="">{document?.insurancePolicyId ? "Attached to insurance policy" : "Choose vehicle"}</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.year} {vehicle.make} {vehicle.model}</option>)}</select></Field>
    <Field label="Document type"><SelectOrCustom label="Document type" value={kind} options={["Manual","Receipt","Photo","Registration","Insurance","Other"]} onChange={setKind} placeholder="e.g. Warranty" emptyLabel="Choose or add a type" /></Field>
    {!document?.insurancePolicyId && Number(vehicleId) > 0 && <Field label="Linked maintenance records" wide><div className="maintenance-link-picker"><input type="search" value={maintenanceSearch} onChange={(event) => setMaintenanceSearch(event.target.value)} placeholder="Search title, system, date, mileage, or person" /><small className="field-note">Select every record that should use this same stored file.</small><div className="maintenance-link-picker__results" role="group" aria-label="Maintenance records">{matchingMaintenance.length ? matchingMaintenance.map((record) => <label key={record.id} data-selected={maintenanceIds.includes(record.id) || undefined}><input type="checkbox" checked={maintenanceIds.includes(record.id)} onChange={() => toggleMaintenance(record.id)} /><span><strong>{record.title}</strong><small>{record.category} · {record.serviceDate} · {formatDistance(record.mileage)}</small></span></label>) : <p className="field-note">No matching maintenance records.</p>}</div></div></Field>}
    {document && (document.maintenanceId || document.projectId) && Number(vehicleId) !== document.vehicleId && <p className="field-note" data-span="wide">Changing vehicle removes this document’s existing maintenance or project links. The document itself is retained.</p>}
    {!document && <Field label="File" wide><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,text/csv,.docx,.xlsx,.odt" onChange={(e) => { const selected = e.target.files?.[0] ?? null; setFile(selected); if (selected && !name.trim()) setName(selected.name.replace(/\.[^.]+$/, "")); }} /><small className="field-note">Images, PDF, text, CSV, Word, Excel, or OpenDocument · 15 MB each. The stored file receives an immutable UUID.</small></Field>}
  </Shell>;
}

export function ReminderDialog({ open, reminder, plans, onClose, onSave, onDelete }: { open: boolean; reminder: Reminder | null; plans: Array<{ id: number; title: string }>; onClose: () => void; onSave: (input: ReminderInput) => Promise<void>; onDelete: (reminder: Reminder) => Promise<void> }) {
  const [form, setForm] = useState({ title: "", dueDate: "", dueMileage: "", notes: "", status: "Active" as Reminder["status"], servicePlanId: "" }); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState("");
  useEffect(() => { if (open) { setForm({ title: reminder?.title ?? "", dueDate: reminder?.dueDate ?? "", dueMileage: inputDistance(reminder?.dueMileage), notes: reminder?.notes ?? "", status: reminder?.status ?? "Active", servicePlanId: reminder?.servicePlanId ? String(reminder.servicePlanId) : "" }); setStatus("idle"); setError(""); } }, [open, reminder]); const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus("loading"); try { await onSave({ title: form.title, dueDate: form.dueDate || null, dueMileage: form.dueMileage ? storedDistance(form.dueMileage) : null, notes: form.notes, status: form.status, servicePlanId: form.servicePlanId ? Number(form.servicePlanId) : null }); setStatus("success"); setTimeout(onClose, 350); } catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message : "The reminder could not be saved."); } };
  return <Shell open={open} title={reminder ? "Edit reminder" : "Add reminder"} kicker="Maintenance schedule" status={status} error={error} onClose={onClose} onSubmit={submit} onDelete={reminder ? async () => { await onDelete(reminder); onClose(); } : undefined}><Field label="Reminder" wide><input value={form.title} onChange={(e) => update("title", e.target.value)} /></Field><Field label="Due date"><input type="date" value={form.dueDate} onChange={(e) => update("dueDate", e.target.value)} /></Field><Field label={`Due mileage (${distanceUnit()})`}><input type="number" min="0" value={form.dueMileage} onChange={(e) => update("dueMileage", e.target.value)} /></Field><Field label="Linked service task"><select value={form.servicePlanId} onChange={(e) => update("servicePlanId", e.target.value)}><option value="">None</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.title}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={(e) => update("status", e.target.value)}>{["Active","Completed","Dismissed"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Notes" wide><textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} /></Field></Shell>;
}
